In [51]:
import numpy as np
import qutip as qt 
import matplotlib.pyplot as plt
from qutip.qip.operations import *

In [70]:
# pulse sequences of various gates

def rzi(theta):
    return np.kron( np.array(rz(theta)), np.identity(2) )

def irz(theta):
    return np.kron( np.identity(2), np.array(rz(theta)) )

def rzz(theta):
    return np.kron( np.array( qt.basis(2,0) * qt.basis(2,0).dag()) , np.array(rz(theta)) ) + np.kron( np.array( qt.basis(2,1) * qt.basis(2,1).dag()) , np.array(rz(-theta)) )

def hadmard():
    return np.array(ry(-1*np.pi/4)) @ np.array(rx(1*np.pi)) @ np.array(ry(1*np.pi/4))

def cz():
    return rzz(-np.pi/2) @  irz(np.pi/2) @ rzi(np.pi/2)

def x():
    return rx(np.pi)



# 1)

## a)

One qubit X gate can be written as $R_x(\pi)$ as 

$X-Gate = \begin{bmatrix}0 & 1 \\ 1 & 0 \end{bmatrix}$

and 

$Rx(\theta) = \begin{bmatrix}\cos(\theta/2) & -\iota\sin(\theta/2) \\ -\iota\sin(\theta/2) & \cos(\theta/2) \end{bmatrix} $

$Ry(\theta) = \begin{bmatrix}\cos(\theta/2) & -\sin(\theta/2) \\ \sin(\theta/2) & \cos(\theta/2) \end{bmatrix} $

$R_x(\pi)$ is calculated below using qutip

In [53]:
print("R_x(\pi) = \n"+str(np.round(np.array(rx(np.pi)),3)))

R_x(\pi) = 
[[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]


Which is X-gate with upto a global phase

## b)

One qubit Hadamard gate can be written as $(R_y(-\pi/2)) -- (R_z(\pi))$  or by using $(R_x(\pi/4)) -- (R_y(\pi)) -- (R_x(-\pi/4))$ as 

$H-Gate = \begin{bmatrix}1/\sqrt{2} & 1/\sqrt{2} \\ 1/\sqrt{2} & -1/\sqrt{2} \end{bmatrix}$


Both values are calculated using qutip below

In [54]:
print("(R_y(-\pi/2)) -- (R_z(\pi)) = \n\n"+str(np.round(np.array(rz(1*np.pi)) @ np.array(ry(-1*np.pi/2)),3)))
print("\n\n")
print("(R_x(\pi/4)) -- (R_y(\pi)) -- (R_x(-\pi/4)) = \n\n"+str(np.round( np.array(ry(-1*np.pi/4)) @ np.array(rx(1*np.pi)) @ np.array(ry(1*np.pi/4)) , 3 )))

(R_y(-\pi/2)) -- (R_z(\pi)) = 

[[ 0.-0.707j  0.-0.707j]
 [-0.-0.707j  0.+0.707j]]



(R_x(\pi/4)) -- (R_y(\pi)) -- (R_x(-\pi/4)) = 

[[ 0.-0.707j  0.-0.707j]
 [-0.-0.707j  0.+0.707j]]


Which is H-gate with upto a global phase

## c)

Two qubit CZ gate can be written as 

$(R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2)) $  

where $R_z(\theta)$ gate can be realized as 

$R_z(\theta) = R_x(-\pi/2) -- R_y(\theta) -- R_x(\pi/2)$

$CZ-Gate = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & -1 \end{bmatrix}$ 


Both values are calculated using qutip below

In [55]:
print("(R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2) = \n\n"+str(np.round( rzz(-np.pi/2) @  irz(np.pi/2) @ rzi(np.pi/2)  ,3)))
print("\n\nand ")
print("R_z(\pi/2) = R_x(-\pi/2) -- R_y(\pi/2) -- R_x(\pi/2) = \n\n"+str(np.round( np.array(rx(np.pi/2)) @ np.array(ry(1*np.pi/2)) @ np.array(rx(-1*np.pi/2)) , 3 )))

(R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2) = 

[[ 0.707-0.707j  0.   +0.j     0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     0.707-0.707j  0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     0.   +0.j     0.707-0.707j  0.   +0.j   ]
 [ 0.   +0.j     0.   +0.j     0.   +0.j    -0.707+0.707j]]


and 
R_z(\pi/2) = R_x(-\pi/2) -- R_y(\pi/2) -- R_x(\pi/2) = 

[[ 0.707-0.707j -0.   +0.j   ]
 [ 0.   +0.j     0.707+0.707j]]


Which is CZ gate upto a global phase. Also the Rz gate can be broken into Rx and Ry gates as shown above (upto a global phase)

## d)

Two qubit CNOT gate can be written as

 $I \otimes H -- CZ -- I \otimes H$
 
  or

  $(R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4)) -- (R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2)) -- (R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4))$ 

$CNOT-Gate = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix}$ 


Both values are calculated using qutip below

In [56]:
print("(R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4)) -- (R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2)) -- (R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4)) = \n\n" + str(np.round(
    np.kron( np.identity(2), np.array(rz(1*np.pi)) )  @  np.kron( np.identity(2),  np.array(ry(-1*np.pi/2))) @ 
    rzz(-np.pi/2) @  irz(np.pi/2) @ rzi(np.pi/2) @
    np.kron( np.identity(2), np.array(rz(1*np.pi)) )  @  np.kron( np.identity(2),  np.array(ry(-1*np.pi/2)))   ,3)))
print("\n\n ")


(R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4)) -- (R_z^{(1)}(\pi/2)) -- (R_z^{(2)}(\pi/2)) -- (R_{zz}(-\pi/2)) -- (R_x^{(2)}(\pi/4)) -- (R_y^{(2)}(\pi)) -- (R_x^{(2)}(-\pi/4)) = 

[[-0.707+0.707j -0.   -0.j     0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j    -0.707+0.707j  0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     0.   +0.j    -0.   -0.j    -0.707+0.707j]
 [ 0.   +0.j     0.   +0.j    -0.707+0.707j -0.   -0.j   ]]


 


Which is CNOT gate upto a global phase.

The calibrated elemental gates we need for this are just the $R_x$ and $R_y$ gates. We can simplify or reduce our pulses if our native architecture supports $R_z$ pulses, however if it is not possible, as is the case with NMR systems, we can decompose our $R_z$ pulses to $R_x$ and $R_y$ pulses as indicated above. We also use $R_{zz}$ pulses which are nothing but a delay and letting the system evolve under the z-hamiltonian. 

# 2)

In [75]:
uf1 = np.kron( np.identity(2), np.identity(2) )

uf2 = ( np.kron(np.identity(2), hadmard()) @ cz() @  np.kron(np.identity(2), hadmard()) )
# remove the global phase of uf2 
uf2 = np.round( uf2*np.abs(uf2[0][0])/(uf2[0][0]) , 3)

uf3 = np.round(np.kron(x(), np.identity(2)) @ uf2 @ np.kron(x(), np.identity(2)) , 3)

uf4 = np.round( np.kron(np.identity(2), x()) , 3)

print(uf1)
print(uf2)
print(uf3)
print(uf4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.-0.j -0.+0.j -0.-0.j -0.-0.j]
 [ 0.+0.j  1.-0.j -0.-0.j -0.-0.j]
 [-0.-0.j -0.-0.j  0.+0.j  1.-0.j]
 [-0.-0.j -0.-0.j  1.-0.j -0.+0.j]]
[[ 0.+0.j -1.+0.j  0.-0.j  0.-0.j]
 [-1.+0.j  0.+0.j  0.-0.j  0.-0.j]
 [ 0.-0.j  0.-0.j -1.+0.j  0.+0.j]
 [ 0.-0.j  0.-0.j  0.+0.j -1.+0.j]]
[[0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.-1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]]


In [105]:
# define ry1, ry2 and ry1bar, ry2bar

def ry1():
    return np.kron( ry(np.pi/2), np.identity(2))
def ry1bar():
    return np.kron( ry(-np.pi/2), np.identity(2))
def ry2():
    return np.kron(np.identity(2), ry(np.pi/2))
def ry2bar():
    return np.kron(np.identity(2), ry(-np.pi/2))




In [106]:
# define rx1, rx2 and rx1bar, rx2bar

def rx1():
    return np.kron( rx(np.pi/2), np.identity(2))
def rx1bar():
    return np.kron( rx(-np.pi/2), np.identity(2))
def rx2():
    return np.kron(np.identity(2), rx(np.pi/2))
def rx2bar():
    return np.kron(np.identity(2), rx(-np.pi/2))




In [85]:
U1 = np.round( ry1bar() @ ry2() @ uf1 @ ry1() @ ry2bar() , 3)
U2 = np.round( ry1bar() @ ry2() @ uf2 @ ry1() @ ry2bar() , 3)
U3 = np.round( ry1bar() @ ry2() @ uf3 @ ry1() @ ry2bar() , 3)
U4 = np.round( ry1bar() @ ry2() @ uf4 @ ry1() @ ry2bar() , 3)


print("U1 is:")
print(U1)
print("\n")
print("U2 is:")
print(U2)
print("\n")
print("U3 is:")
print(U3)
print("\n")
print("U4 is:")
print(U4)

U1 is:
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


U2 is:
[[ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j -0.+0.j]
 [-1.+0.j  0.+0.j -0.+0.j  0.+0.j]
 [ 0.+0.j -0.+0.j  0.+0.j  1.+0.j]]


U3 is:
[[ 0.+0.j -0.+0.j -1.+0.j  0.+0.j]
 [-0.+0.j -1.+0.j  0.+0.j -0.+0.j]
 [-1.+0.j  0.+0.j -0.+0.j -0.+0.j]
 [ 0.+0.j -0.+0.j -0.+0.j -1.+0.j]]


U4 is:
[[0.+1.j 0.-0.j 0.+0.j 0.+0.j]
 [0.-0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+1.j 0.-0.j]
 [0.+0.j 0.+0.j 0.-0.j 0.-1.j]]


# 3)
## Two qubit Deutsch-Jozsa

Step 1: 
State prearation $\ket{00}$: Apply one of the P0, P1, P2 pulses (in separate instances of experiment run) where 

P0 = Identity(4x4)

P1 = CNOT(1,2) . CNOT(2,1)

P2 = CNOT(2,1) . CNOT(1,2) 

in each separate instance and then average results for all state preparation

Step 2:
Apply the $U_k$ unitaries calculated earlier

Step 3: 
Measure qubit 1 (or calculate the output density matrix)

Step 4:
Take average of density matrices for P0, P1, P2

(Note: We don't need to apply X gates or the Hadamards as is also suggested by the paper, because we factor it into our $U_k$ uniatry pulses)



In [98]:
def cnot12():
    return ( np.kron(np.identity(2), hadmard()) @ cz() @  np.kron(np.identity(2), hadmard()) )
def cnot21():
    return ( np.kron( hadmard(), np.identity(2)) @ cz() @  np.kron( hadmard(), np.identity(2)) )

def P0():
    return np.kron(np.identity(2), np.identity(2))

def P1():
    return cnot12() @ cnot21()

def P2():
    return cnot21() @ cnot12()

def DJ_circuit(Pk, oracle):
    return oracle @ Pk

def output_density_matrix(input_density, oracle):
    P0_measure = DJ_circuit(P0(), oracle) @ input_density @ np.conjugate(np.transpose(DJ_circuit(P0(), oracle)))
    P1_measure = DJ_circuit(P1(), oracle) @ input_density @ np.conjugate(np.transpose(DJ_circuit(P1(), oracle)))
    P2_measure = DJ_circuit(P2(), oracle) @ input_density @ np.conjugate(np.transpose(DJ_circuit(P2(), oracle)))

    return np.round((P0_measure + P1_measure + P2_measure)/3 , 5)



### U1 output

In [101]:
thermal_density_matrix = 0.25*np.identity(4) + 10**(-4)*np.diag([5, 3, -3, -5  ])

print(output_density_matrix(thermal_density_matrix, U1))

print("\n\nThe relative population is :")

print((output_density_matrix(thermal_density_matrix, U1) - 0.25*np.identity(4))*10**(4))

[[ 0.2505 +0.j -0.     +0.j -0.     +0.j -0.     +0.j]
 [-0.     -0.j  0.24983+0.j  0.     +0.j  0.     +0.j]
 [-0.     -0.j  0.     -0.j  0.24983+0.j  0.     +0.j]
 [-0.     -0.j  0.     -0.j  0.     -0.j  0.24983-0.j]]


The relative population is :
[[ 5. +0.j -0. +0.j -0. +0.j -0. +0.j]
 [ 0. -0.j -1.7+0.j  0. +0.j  0. +0.j]
 [ 0. -0.j  0. +0.j -1.7+0.j  0. +0.j]
 [ 0. -0.j  0. +0.j  0. +0.j -1.7-0.j]]


We see the probability of state $\ket{00}$ is highest thus we measure qubit 1 in state $\ket{0}$. Therefore this is a constant function.

### U2 output

In [102]:
thermal_density_matrix = 0.25*np.identity(4) + 10**(-4)*np.diag([5, 3, -3, -5  ])

print(output_density_matrix(thermal_density_matrix, U2))

print("\n\nThe relative population is :")

print((output_density_matrix(thermal_density_matrix, U2) - 0.25*np.identity(4))*10**(4))

[[ 0.24983+0.j -0.     +0.j -0.     -0.j -0.     -0.j]
 [-0.     -0.j  0.24983+0.j  0.     +0.j  0.     +0.j]
 [-0.     +0.j  0.     -0.j  0.2505 +0.j  0.     -0.j]
 [-0.     +0.j  0.     -0.j  0.     +0.j  0.24983-0.j]]


The relative population is :
[[-1.7+0.j -0. +0.j  0. -0.j  0. -0.j]
 [ 0. -0.j -1.7+0.j  0. +0.j  0. +0.j]
 [-0. +0.j  0. +0.j  5. +0.j  0. +0.j]
 [-0. +0.j  0. +0.j  0. +0.j -1.7-0.j]]


We see the probability of state $\ket{10}$ is highest thus we measure qubit 1 in state $\ket{1}$. Therefore this is a constant function.

### U3 output

In [103]:
thermal_density_matrix = 0.25*np.identity(4) + 10**(-4)*np.diag([5, 3, -3, -5  ])

print(output_density_matrix(thermal_density_matrix, U3))

print("\n\nThe relative population is :")

print((output_density_matrix(thermal_density_matrix, U3) - 0.25*np.identity(4))*10**(4))

[[ 0.24983+0.j  0.     -0.j -0.     -0.j  0.     +0.j]
 [ 0.     +0.j  0.24983+0.j -0.     -0.j  0.     +0.j]
 [-0.     +0.j -0.     +0.j  0.2505 +0.j -0.     +0.j]
 [ 0.     -0.j  0.     -0.j -0.     -0.j  0.24983-0.j]]


The relative population is :
[[-1.7+0.j  0. +0.j  0. -0.j  0. +0.j]
 [ 0. +0.j -1.7+0.j  0. -0.j  0. +0.j]
 [-0. +0.j -0. +0.j  5. +0.j -0. +0.j]
 [ 0. +0.j  0. +0.j  0. -0.j -1.7-0.j]]


We see the probability of state $\ket{10}$ is highest thus we measure qubit 1 in state $\ket{1}$. Therefore this is a constant function.

### U4 output

In [104]:
thermal_density_matrix = 0.25*np.identity(4) + 10**(-4)*np.diag([5, 3, -3, -5  ])

print(output_density_matrix(thermal_density_matrix, U4))

print("\n\nThe relative population is :")

print((output_density_matrix(thermal_density_matrix, U4) - 0.25*np.identity(4))*10**(4))

[[ 0.2505 +0.j  0.     -0.j -0.     +0.j  0.     -0.j]
 [ 0.     +0.j  0.24983+0.j -0.     -0.j  0.     +0.j]
 [-0.     -0.j -0.     +0.j  0.24983+0.j -0.     -0.j]
 [ 0.     +0.j  0.     -0.j -0.     +0.j  0.24983-0.j]]


The relative population is :
[[ 5. +0.j  0. +0.j -0. +0.j  0. +0.j]
 [ 0. +0.j -1.7+0.j  0. -0.j  0. +0.j]
 [ 0. -0.j -0. +0.j -1.7+0.j  0. -0.j]
 [ 0. +0.j  0. +0.j -0. +0.j -1.7-0.j]]


We see the probability of state $\ket{00}$ is highest thus we measure qubit 1 in state $\ket{0}$. Therefore this is a constant function.

# 4)

## Grover's Algorithm

Step 1: 
State prearation $\ket{00}$: Apply one of the P0, P1, P2 pulses (in separate instances of experiment run) where 

P0 = Identity(4x4)

P1 = CNOT(1,2) . CNOT(2,1)

P2 = CNOT(2,1) . CNOT(1,2) 

in each separate instance and then average results for all state preparation

Step 2:
Apply the $H \otimes H$ on circuit

Step 3:
Apply the 'G' pulses on circuit

Step 3: 
Measure qubits form the density matrix

Step 4:
Take average of density matrices for P0, P1, P2

(Note: We don't need to apply X gates or the Hadamards as is also suggested by the paper, because we factor it into our $U_k$ uniatry pulses)



In [111]:
grover_oracle = ry1() @  rx1() @ ry1bar() @ ry2() @ rx2() @ ry2bar() @ rzz(np.pi/2) 

print(np.round(grover_oracle, 3))

[[ 0.707+0.707j  0.   -0.j     0.   -0.j    -0.   +0.j   ]
 [ 0.   -0.j     0.707+0.707j -0.   -0.j    -0.   -0.j   ]
 [ 0.   -0.j    -0.   -0.j     0.707+0.707j -0.   +0.j   ]
 [-0.   +0.j     0.   -0.j     0.   -0.j    -0.707-0.707j]]


In [114]:
P = ry1() @  rx1bar() @ ry1bar() @ ry2() @ rx2bar() @ ry2bar() @ rzz(np.pi/2) 

print(np.round(P, 3))

[[-0.707-0.707j -0.   +0.j     0.   +0.j    -0.   +0.j   ]
 [ 0.   -0.j     0.707+0.707j -0.   -0.j     0.   +0.j   ]
 [ 0.   +0.j    -0.   -0.j     0.707+0.707j -0.   +0.j   ]
 [-0.   +0.j    -0.   +0.j    -0.   +0.j     0.707+0.707j]]


In [119]:
G = np.kron(hadmard(), hadmard()) @ P @ np.kron(hadmard(), hadmard()) @ grover_oracle

print(np.round(G,3))

[[-0.+0.5j  0.-0.5j  0.-0.5j -0.+0.5j]
 [ 0.-0.5j  0.+0.5j  0.-0.5j -0.+0.5j]
 [ 0.-0.5j  0.-0.5j  0.+0.5j -0.+0.5j]
 [-0.-0.5j -0.-0.5j -0.-0.5j -0.-0.5j]]


In [132]:
def grover_circuit(Pk):
    return G @ np.kron((hadmard()), (hadmard())) @ Pk

In [133]:
def output_density_matrix_grover(input_density_matrix):
    P0_measure = grover_circuit(P0()) @ input_density_matrix @ np.conjugate(np.transpose(grover_circuit((P0()))))
    P1_measure = grover_circuit(P1()) @ input_density_matrix @ np.conjugate(np.transpose(grover_circuit((P1()))))
    P2_measure = grover_circuit(P2()) @ input_density_matrix @ np.conjugate(np.transpose(grover_circuit((P2()))))

    return (P0_measure + P1_measure + P2_measure)/3


In [139]:
print(np.round(output_density_matrix_grover(thermal_density_matrix), 6))
print("\n\nThe relative population is :")

print((np.round(output_density_matrix_grover(thermal_density_matrix), 6) - 0.25*np.identity(4))*10**(4))

[[ 0.249833+0.j  0.      -0.j -0.      -0.j  0.      -0.j]
 [ 0.      +0.j  0.249833+0.j -0.      +0.j -0.      +0.j]
 [-0.      +0.j -0.      -0.j  0.249833+0.j -0.      +0.j]
 [ 0.      +0.j -0.      -0.j -0.      -0.j  0.2505  +0.j]]


The relative population is :
[[-1.67+0.j  0.  +0.j  0.  -0.j  0.  +0.j]
 [ 0.  +0.j -1.67+0.j -0.  +0.j -0.  +0.j]
 [-0.  +0.j  0.  -0.j -1.67+0.j -0.  +0.j]
 [ 0.  +0.j  0.  -0.j  0.  -0.j  5.  +0.j]]


We see the probability of state $\ket{11}$ is highest and this is our output.